# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\etc\layout.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 544)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 481, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.figuareLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.figuareLayout.setContentsMargins(0, 0, 0, 0)
        self.figuareLayout.setObjectName("figuareLayout")
        self.excuteButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.excuteButton.setGeometry(QtCore.QRect(530, 160, 191, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.excuteButton.setFont(font)
        self.excuteButton.setIconSize(QtCore.QSize(60, 60))
        self.excuteButton.setObjectName("excuteButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(720, 180, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.clearButton.setFont(font)
        self.clearButton.setObjectName("clearButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(520, 20, 281, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.errorrateLCD = QtWidgets.QLCDNumber(self.groupBox_2)
        self.errorrateLCD.setGeometry(QtCore.QRect(160, 30, 111, 71))
        self.errorrateLCD.setObjectName("errorrateLCD")
        self.comboBox = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(520, 240, 271, 251))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.learningrateEdit = QtWidgets.QLineEdit(self.groupBox)
        self.learningrateEdit.setGeometry(QtCore.QRect(160, 30, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.learningrateEdit.setFont(font)
        self.learningrateEdit.setObjectName("learningrateEdit")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.stepsEdit = QtWidgets.QLineEdit(self.groupBox)
        self.stepsEdit.setGeometry(QtCore.QRect(160, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Bell MT")
        font.setPointSize(12)
        self.stepsEdit.setFont(font)
        self.stepsEdit.setObjectName("stepsEdit")
        self.dial = QtWidgets.QDial(self.groupBox)
        self.dial.setGeometry(QtCore.QRect(150, 120, 101, 91))
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.dialLabel = QtWidgets.QLabel(self.groupBox)
        self.dialLabel.setGeometry(QtCore.QRect(165, 150, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dialLabel.setFont(font)
        self.dialLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dialLabel.setObjectName("dialLabel")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton.setGeometry(QtCore.QRect(30, 180, 90, 16))
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 200, 90, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 220, 101, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.dial_2 = QtWidgets.QDial(self.groupBox)
        self.dial_2.setEnabled(False)
        self.dial_2.setGeometry(QtCore.QRect(219, 190, 51, 71))
        self.dial_2.setNotchesVisible(False)
        self.dial_2.setObjectName("dial_2")
        self.dialLabel2 = QtWidgets.QLabel(self.groupBox)
        self.dialLabel2.setGeometry(QtCore.QRect(220, 215, 51, 20))
        self.dialLabel2.setText("")
        self.dialLabel2.setAlignment(QtCore.Qt.AlignCenter)
        self.dialLabel2.setObjectName("dialLabel2")
        self.verticalLayoutWidget.raise_()
        self.excuteButton.raise_()
        self.clearButton.raise_()
        self.groupBox_2.raise_()
        self.label.raise_()
        self.groupBox.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionGoto_gitHub = QtWidgets.QAction(MainWindow)
        self.actionGoto_gitHub.setObjectName("actionGoto_gitHub")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionGoto_gitHub)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project2. Regression Analysis"))
        self.excuteButton.setText(_translate("MainWindow", "Process"))
        self.clearButton.setText(_translate("MainWindow", "Clear"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Error Rate"))
        self.comboBox.setItemText(0, _translate("MainWindow", "All"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Linear"))
        self.groupBox.setTitle(_translate("MainWindow", "Option"))
        self.label.setText(_translate("MainWindow", "Learning Rate"))
        self.learningrateEdit.setText(_translate("MainWindow", "0.01"))
        self.label_2.setText(_translate("MainWindow", "Steps"))
        self.stepsEdit.setText(_translate("MainWindow", "500"))
        self.label_3.setText(_translate("MainWindow", "Regularization"))
        self.dialLabel.setText(_translate("MainWindow", "0"))
        self.radioButton.setText(_translate("MainWindow", "Ridge"))
        self.radioButton_2.setText(_translate("MainWindow", "Lasso"))
        self.radioButton_3.setText(_translate("MainWindow", "Elastic Net"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionGoto_gitHub.setText(_translate("MainWindow", "Goto gitHub"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

